{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "<div align=\"center\"><img src=\"./images/LKYCIC_Header.jpg\"></div>"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Transform Shapefile into KML and imported into Google Map"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 50,
   "metadata": {},
   "outputs": [],
   "source": [
    "import geopandas as gpd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 57,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "         Name PT_CODE       lat         lng                   geometry\n",
      "0  South View     BP2  1.380260  103.745285  POINT (103.74528 1.38026)\n",
      "1   Keat Hong     BP3  1.378603  103.749021   POINT (103.74902 1.3786)\n",
      "2   Teck Whye     BP4  1.376671  103.753647  POINT (103.75365 1.37667)\n",
      "3     Phoenix     BP5  1.378366  103.757716  POINT (103.75772 1.37837)\n",
      "4       Petir     BP7  1.377276  103.767341  POINT (103.76734 1.37728)\n"
     ]
    }
   ],
   "source": [
    "# Read a shapefile\n",
    "shapefile_path = \"data/SG_MRT/MRT_LRT_Stations.shp\"\n",
    "shapefile_data = gpd.read_file(shapefile_path)\n",
    "\n",
    "print(shapefile_data.head())"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 58,
   "metadata": {},
   "outputs": [],
   "source": [
    "# divided PT_CODE into a list by the delimiter \"/\"\n",
    "shapefile_data['PT_CODE_List'] = shapefile_data['PT_CODE'].str.split('/')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 59,
   "metadata": {},
   "outputs": [],
   "source": [
    "# get all the pt code in the column PT_CODE\n",
    "all_pt_code = []\n",
    "for pt_code in shapefile_data['PT_CODE_List']:\n",
    "    all_pt_code.extend(pt_code)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 60,
   "metadata": {},
   "outputs": [],
   "source": [
    "import re\n",
    "\n",
    "# remove numbers in each code in the list\n",
    "mrt_codes = []\n",
    "for code in all_pt_code:\n",
    "    mrt_codes.append(re.sub(r'[0-9]', '', code))\n",
    "\n",
    "# remove duplicates\n",
    "mrt_codes = list(set(mrt_codes))\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 61,
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  super().__setitem__(key, value)\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC12']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS17', 'CC15']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC19', 'DT9']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC2']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC22', 'EW21']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC17', 'TE9']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC8']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS24', 'NE6', 'CC1']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC3']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC20']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE1', 'CC29']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC25']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC21']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC24']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC27']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC14']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC10', 'DT26']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC16']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC7']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC5']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC23']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC26']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW8', 'CC9']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC4', 'DT15']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE12', 'CC13']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC6']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC11']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC28']' of field CC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  super().__setitem__(key, value)\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['SE1']' of field SE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['SE2']' of field SE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['SE3']' of field SE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['SE4']' of field SE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['SE5']' of field SE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  super().__setitem__(key, value)\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CG2']' of field CG.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CG1', 'DT35']' of field CG.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  super().__setitem__(key, value)\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE16', 'STC']' of field STC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  super().__setitem__(key, value)\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['PE1']' of field PE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['PE2']' of field PE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['PE3']' of field PE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['PE4']' of field PE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['PE5']' of field PE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['PE6']' of field PE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['PE7']' of field PE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  super().__setitem__(key, value)\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['PW7']' of field PW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['PW6']' of field PW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['PW5']' of field PW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['PW4']' of field PW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['PW3']' of field PW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['PW2']' of field PW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['PW1']' of field PW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  super().__setitem__(key, value)\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['TE7']' of field TE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['TE5']' of field TE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['TE4']' of field TE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['TE6']' of field TE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['TE8']' of field TE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC17', 'TE9']' of field TE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS9', 'TE2']' of field TE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['TE1']' of field TE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['TE3']' of field TE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  super().__setitem__(key, value)\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CE1', 'DT16']' of field CE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS27', 'CE2']' of field CE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  super().__setitem__(key, value)\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW9']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW5']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW27']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW12', 'DT14']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC22', 'EW21']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW25']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW13', 'NS25']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW23']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW20']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW22']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW7']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW30']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW29']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW24', 'NS1']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW10']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW6']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW26']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW11']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW16', 'NE3']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW1']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW8', 'CC9']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW28']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW19']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW14', 'NS26']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW18']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW3']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW2', 'DT32']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW4']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW15']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW17']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW31']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW33']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW32']' of field EW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  super().__setitem__(key, value)\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['BP2']' of field BP.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['BP3']' of field BP.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['BP4']' of field BP.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['BP5']' of field BP.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['BP7']' of field BP.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['BP8']' of field BP.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['BP9']' of field BP.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['BP10']' of field BP.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['BP11']' of field BP.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['BP12']' of field BP.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['BP13']' of field BP.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['BP14']' of field BP.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['BP6', 'DT1']' of field BP.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS4', 'BP1']' of field BP.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  super().__setitem__(key, value)\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE9']' of field NE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE15']' of field NE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE4', 'DT19']' of field NE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE5']' of field NE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS24', 'NE6', 'CC1']' of field NE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE8']' of field NE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE1', 'CC29']' of field NE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE14']' of field NE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE13']' of field NE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE7', 'DT12']' of field NE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW16', 'NE3']' of field NE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE10']' of field NE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE17', 'PTC']' of field NE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE16', 'STC']' of field NE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE12', 'CC13']' of field NE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE11']' of field NE.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  super().__setitem__(key, value)\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS10']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS16']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS17', 'CC15']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS18']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS2']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS3']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS12']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS4', 'BP1']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW13', 'NS25']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS24', 'NE6', 'CC1']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW24', 'NS1']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS14']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS7']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS27', 'CE2']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS28']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS8']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS21', 'DT11']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS20']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS22']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW14', 'NS26']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS11']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS23']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS19']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS9', 'TE2']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS5']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS15']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS13']' of field NS.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  super().__setitem__(key, value)\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CE1', 'DT16']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT5']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT29']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT30']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT21']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT23']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC19', 'DT9']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW12', 'DT14']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['BP6', 'DT1']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT2']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE4', 'DT19']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT17']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CG1', 'DT35']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT20']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT24']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT3']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT22']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT28']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT6']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE7', 'DT12']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC10', 'DT26']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT25']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NS21', 'DT11']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['CC4', 'DT15']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT13']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT7']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT10']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['EW2', 'DT32']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT33']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT31']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT8']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT18']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT27']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['DT34']' of field DT.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  super().__setitem__(key, value)\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['SW8']' of field SW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['SW7']' of field SW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['SW6']' of field SW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['SW5']' of field SW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['SW4']' of field SW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['SW3']' of field SW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['SW2']' of field SW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['SW1']' of field SW.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/geopandas/geodataframe.py:1819: SettingWithCopyWarning: \n",
      "A value is trying to be set on a copy of a slice from a DataFrame.\n",
      "Try using .loc[row_indexer,col_indexer] = value instead\n",
      "\n",
      "See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy\n",
      "  super().__setitem__(key, value)\n",
      "/home/bywsl/.virtualenvs/geospatial/lib/python3.12/site-packages/pyogrio/raw.py:723: RuntimeWarning: Value '['NE17', 'PTC']' of field PTC.lat parsed incompletely to real 0.\n",
      "  ogr_write(\n"
     ]
    }
   ],
   "source": [
    "list_mrt_gpd = dict()\n",
    "\n",
    "for mrt_code in mrt_codes:\n",
    "    mrt_gpd = shapefile_data[shapefile_data['PT_CODE'].str.contains(mrt_code)]\n",
    "    list_mrt_gpd[mrt_code] = mrt_gpd\n",
    "    # save the data as kml with the name of the mrt_code\n",
    "    mrt_gpd['index'] = mrt_gpd.index\n",
    "    # save as csv\n",
    "    mrt_gpd.to_csv(f\"data/SG_MRT/{mrt_code}.csv\", index=False)\n",
    "    mrt_gpd.to_file(f\"data/SG_MRT/{mrt_code}.kml\", driver='KML')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 49,
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Name</th>\n",
       "      <th>PT_CODE</th>\n",
       "      <th>geometry</th>\n",
       "      <th>PT_CODE_List</th>\n",
       "      <th>index</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>130</th>\n",
       "      <td>Punggol</td>\n",
       "      <td>NE17/PTC</td>\n",
       "      <td>POINT (103.90237 1.40519)</td>\n",
       "      <td>[NE17, PTC]</td>\n",
       "      <td>130</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "        Name   PT_CODE                   geometry PT_CODE_List  index\n",
       "130  Punggol  NE17/PTC  POINT (103.90237 1.40519)  [NE17, PTC]    130"
      ]
     },
     "execution_count": 49,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "mrt_gpd"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "geospatial",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.3"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
